// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUISampleFramework.UIMaps.HomepageUIClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class HomepageUI
    {
        
        #region Properties
        public BingBrowser BingBrowser
        {
            get
            {
                if ((this.mBingBrowser == null))
                {
                    this.mBingBrowser = new BingBrowser();
                }
                return this.mBingBrowser;
            }
        }
        #endregion
        
        #region Fields
        private BingBrowser mBingBrowser;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BingBrowser : BrowserWindow
    {
        
        public BingBrowser()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public BingHomepage BingHomepage
        {
            get
            {
                if ((this.mBingHomepage == null))
                {
                    this.mBingHomepage = new BingHomepage(this);
                }
                return this.mBingHomepage;
            }
        }
        #endregion
        
        #region Fields
        private BingHomepage mBingHomepage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BingHomepage : HtmlDocument
    {
        
        public BingHomepage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Bing";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.bing.com/";
            this.WindowTitles.Add("Bing");
            #endregion
        }
        
        #region Properties
        public HtmlEdit SearchEdit
        {
            get
            {
                if ((this.mSearchEdit == null))
                {
                    this.mSearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mSearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "sb_form_q";
                    this.mSearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Enter your search term";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "sw_qbox";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=sb_form_q class=sw_qbox title=\"Enter ";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mSearchEdit.WindowTitles.Add("Bing");
                    #endregion
                }
                return this.mSearchEdit;
            }
        }
        
        public HtmlInputButton SearchButton
        {
            get
            {
                if ((this.mSearchButton == null))
                {
                    this.mSearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mSearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "sb_form_go";
                    this.mSearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = "go";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Search";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "sw_qbtn";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=sb_form_go class=sw_qbtn title=Search";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mSearchButton.WindowTitles.Add("Bing");
                    #endregion
                }
                return this.mSearchButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mSearchEdit;
        
        private HtmlInputButton mSearchButton;
        #endregion
    }
}
