// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUISampleFramework.UIMaps.SearchResultsUIClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class SearchResultsUI
    {
        
        #region Properties
        public BingSearchResultsBrowser BingSearchResultsBrowser
        {
            get
            {
                if ((this.mBingSearchResultsBrowser == null))
                {
                    this.mBingSearchResultsBrowser = new BingSearchResultsBrowser();
                }
                return this.mBingSearchResultsBrowser;
            }
        }
        #endregion
        
        #region Fields
        private BingSearchResultsBrowser mBingSearchResultsBrowser;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BingSearchResultsBrowser : BrowserWindow
    {
        
        public BingSearchResultsBrowser()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Testing - Bing";
            this.WindowTitles.Add("Testing - Bing");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public BingResultsPage BingResultsPage
        {
            get
            {
                if ((this.mBingResultsPage == null))
                {
                    this.mBingResultsPage = new BingResultsPage(this);
                }
                return this.mBingResultsPage;
            }
        }
        #endregion
        
        #region Fields
        private BingResultsPage mBingResultsPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BingResultsPage : HtmlDocument
    {
        
        public BingResultsPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Testing - Bing";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/search";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.bing.com/search?q=Testing&form=QBLH&filt=all";
            this.WindowTitles.Add("Testing - Bing");
            #endregion
        }
        
        #region Properties
        public HtmlDiv NoResultsPane
        {
            get
            {
                if ((this.mNoResultsPane == null))
                {
                    this.mNoResultsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mNoResultsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "no_results";
                    this.mNoResultsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mNoResultsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "We did not find any results for 43243243";
                    this.mNoResultsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mNoResultsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mNoResultsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=no_results";
                    this.mNoResultsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "21";
                    this.mNoResultsPane.WindowTitles.Add("43243243242432gfihygi7847089^(*&(*&(&*&)(&)(&)(&)()(dfkjdfkjfhdsjfhdsfdsf&^*&^*&(" +
                            "^*(^*(^&*(*& -");
                    #endregion
                }
                return this.mNoResultsPane;
            }
        }
        
        public HtmlInputButton SearchButton
        {
            get
            {
                if ((this.mSearchButton == null))
                {
                    this.mSearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mSearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "sb_form_go";
                    this.mSearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = "go";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = null;
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Search";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "sw_qbtn";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=sb_form_go class=sw_qbtn title=Search";
                    this.mSearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mSearchButton.WindowTitles.Add("TEsting - Bing");
                    #endregion
                }
                return this.mSearchButton;
            }
        }
        
        public HtmlEdit SearchEdit
        {
            get
            {
                if ((this.mSearchEdit == null))
                {
                    this.mSearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mSearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "sb_form_q";
                    this.mSearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Enter your search term";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "sw_qbox";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=sb_form_q class=sw_qbox title=\"Enter ";
                    this.mSearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mSearchEdit.WindowTitles.Add("TEsting - Bing");
                    #endregion
                }
                return this.mSearchEdit;
            }
        }
        
        public RelatedSearchesPane RelatedSearchesPane
        {
            get
            {
                if ((this.mRelatedSearchesPane == null))
                {
                    this.mRelatedSearchesPane = new RelatedSearchesPane(this);
                }
                return this.mRelatedSearchesPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mNoResultsPane;
        
        private HtmlInputButton mSearchButton;
        
        private HtmlEdit mSearchEdit;
        
        private RelatedSearchesPane mRelatedSearchesPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class RelatedSearchesPane : HtmlDiv
    {
        
        public RelatedSearchesPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "sw_rel";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Related searches\r\nGED Testing\r\nProduct T";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "sw_menu";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=sw_rel class=sw_menu";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "30";
            this.WindowTitles.Add("Testing - Bing");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink RelatedSearchesHyperlink
        {
            get
            {
                if ((this.mRelatedSearchesHyperlink == null))
                {
                    this.mRelatedSearchesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mRelatedSearchesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "";
                    this.mRelatedSearchesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = "";
                    this.mRelatedSearchesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "";
                    this.mRelatedSearchesHyperlink.WindowTitles.Add("Testing - Bing");
                    #endregion
                }
                return this.mRelatedSearchesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mRelatedSearchesHyperlink;
        #endregion
    }
}
